//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingBiao.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bid_PBEntities : DbContext
    {
        public Bid_PBEntities()
            : base("name=Bid_PBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PingBiao_BiaoDuan> PingBiao_BiaoDuan { get; set; }
        public virtual DbSet<PingBiao_BiaoDuanExt> PingBiao_BiaoDuanExt { get; set; }
        public virtual DbSet<PingBiao_BiaoJue> PingBiao_BiaoJue { get; set; }
        public virtual DbSet<PingBiao_Eval_BaojiaMark> PingBiao_Eval_BaojiaMark { get; set; }
        public virtual DbSet<PingBiao_Eval_BiaoJiaBJB> PingBiao_Eval_BiaoJiaBJB { get; set; }
        public virtual DbSet<PingBiao_KaiBiaoTouBiao> PingBiao_KaiBiaoTouBiao { get; set; }
        public virtual DbSet<PingBiao_PW_LoginInfo> PingBiao_PW_LoginInfo { get; set; }
        public virtual DbSet<PingBiao_Pw_Mark> PingBiao_Pw_Mark { get; set; }
    }
}
