//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingBiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PingBiao_BiaoJue
    {
        public string BelongXiaQuCode { get; set; }
        public string OperateUserName { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public int Row_ID { get; set; }
        public string YearFlag { get; set; }
        public string RowGuid { get; set; }
        public string ItemGuid { get; set; }
        public string BiaoDuanGuid { get; set; }
        public string BiaoJueTitle { get; set; }
        public string BiaoJueContent { get; set; }
        public string SendUserGuid { get; set; }
        public string SendUserName { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string LastResult { get; set; }
        public string BiaoDuanName { get; set; }
        public string BiaoJueYJ { get; set; }
    }
}
